apiVersion: v1
kind: Pod
metadata:
  name: label-checker
spec:
  serviceAccountName: label-reader
  volumes:
  - name: output
    emptyDir: {}

  initContainers:
  - name: init-label-file
    image: busybox
    command: ["sh", "-c", "touch /tmp/labels.txt && chmod 666 /tmp/labels.txt"]
    volumeMounts:
    - name: output
      mountPath: /tmp

  containers:
  - name: label-checker
    image: labels:v2
    command: ["bash", "/tmp/script.sh"]
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - name: output
      mountPath: /tmp/labels.txt
      subPath: labels.txt
  restartPolicy: Never
