# ===========================================================
# Fichier de configuration Prometheus pour la supervision des NODES Kubernetes
# À utiliser pour définir les règles d'alerte sur les ressources des nœuds (CPU, mémoire, disque, etc.)
# ⚠️ Ce fichier s'applique via Helm (ex : helm upgrade ...) et NON via kubectl apply
#     car il fait partie de la configuration chart/kube-prometheus-stack.
# Différence avec le précédent :
#   - Le précédent (PrometheusRule) ne concerne que les PODS et s'applique avec kubectl apply.
#   - Celui-ci configure à la fois le scraping des métriques des nœuds et les règles d'alerte sur les NODES,
#     et doit être injecté dans la release Helm de Prometheus (souvent via values.yaml ou un fichier custom).
# ===========================================================

prometheus: # Ce bloc configure Prometheus via Helm (chart kube-prometheus-stack)
  prometheusSpec:
    additionalScrapeConfigs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
        scrape_interval: 15s
      - job_name: 'kubelet-cadvisor'
        scheme: https
        tls_config:
          insecure_skip_verify: true
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        kubernetes_sd_configs:
          - role: node
        metrics_path: /metrics/cadvisor
        scrape_interval: 15s
        relabel_configs:
          - source_labels: [__address__]
            regex: '(.*):10250'
            replacement: '${1}:10250'
            target_label: __address__

additionalPrometheusRules:
  - name: pod-cpu-usage-levels
    groups:
      - name: pod-cpu.rules
        rules:
          # Règles d'alerte sur les pods (CPU)
          - alert: CpuNormal
            expr: |
              sum by(pod, namespace) (
                rate(container_cpu_usage_seconds_total[5m])
              ) < 0.8
            for: 5m
            labels:
              severity: info
            annotations:
              summary: "CPU usage is normal on pod {{ $labels.pod }} (namespace {{ $labels.namespace }})"
              description: "CPU usage is below 80% for more than 5 minutes on pod {{ $labels.pod }}."
              pod: "{{ $labels.pod }}"
              namespace: "{{ $labels.namespace }}"
              cpu: "{{ printf \"%.2f\" $value }}"

          - alert: HighCpuUsage
            expr: |
              sum by(pod, namespace) (
                rate(container_cpu_usage_seconds_total[5m])
              ) >= 0.8 and
              sum by(pod, namespace) (
                rate(container_cpu_usage_seconds_total[5m])
              ) < 1.0
            for: 5m
            labels:
              severity: warning
            annotations:
              summary: "High CPU usage on pod {{ $labels.pod }} (namespace {{ $labels.namespace }})"
              description: "CPU usage is between 80% and 100% for more than 5 minutes."
              pod: "{{ $labels.pod }}"
              namespace: "{{ $labels.namespace }}"
              cpu: "{{ printf \"%.2f\" $value }}"

          - alert: CpuFailure
            expr: |
              sum by(pod, namespace) (
                rate(container_cpu_usage_seconds_total[5m])
              ) >= 1.0
            for: 1m
            labels:
              severity: critical
            annotations:
              summary: "CPU FAILURE on pod {{ $labels.pod }} (namespace {{ $labels.namespace }})"
              description: "CPU usage exceeded 100% for more than 1 minute!"
              pod: "{{ $labels.pod }}"
              namespace: "{{ $labels.namespace }}"
              cpu: "{{ printf \"%.2f\" $value }}"

          # Règle d'alerte sur l'utilisation du disque des NODES
          - alert: HighDiskUsage
            expr: 100 * (node_filesystem_size_bytes{fstype!~"tmpfs|overlay"} - node_filesystem_free_bytes{fstype!~"tmpfs|overlay"}) / node_filesystem_size_bytes{fstype!~"tmpfs|overlay"} > 80
            for: 5m
            labels:
              severity: critical
            annotations:
              summary: "Disk usage is high on instance {{ $labels.instance }} (mountpoint {{ $labels.mountpoint }})"
              description: "Disk usage is above 80% for more than 5 minutes on {{ $labels.mountpoint }}."

          # Règle d'alerte sur la mémoire des NODES
          - alert: HighMemoryUsage
            expr: 100 * (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) > 80
            for: 5m
            labels:
              severity: critical
            annotations:
              summary: "Memory usage is high on instance {{ $labels.instance }}"
              description: "Memory usage is above 80% for more than 5 minutes on the node."
